// --- STATE & DUMMY DATA ---
const dummyBrands = [
    { name: "Elevatesports1", logo: "🏓Elevate Sports" }
    { name: "Butterfly", logo: "🦋 Butterfly" },
    { name: "Stiga", logo: "⭐ Stiga" },
    { name: "DHS", logo: "🏓 DHS" },
    { name: "Tibhar", logo: "🔥 Tibhar" },
    { name: "Yasaka", logo: "🌟 Yasaka" },
    { name: "Donic", logo: "⚡ Donic" },
    { name: "Joola", logo: "🎯 Joola" },
    { name: "Xiom", logo: "🚀 Xiom" },
    { name: "Nittaku", logo: "🎾 Nittaku" },
    { name: "Andro", logo: "💥 Andro" },
    { name: "Victas", logo: "🎉 Victas" },
    { name: "Friendship", logo: "🤝 Friendship" },
    { name: "Double Fish", logo: "🐟 Double Fish" },
    { name: "Flick", logo: "🎬 Flick" },
    { name: "Loki", logo: "👹 Loki" },
    { name: "Spinfire", logo: "🔥 Spinfire" },
    { name: "Stag", logo: "🦌 Stag" }
];

const dummyProducts = [
    {
        id: 1, 
        brand: "Butterfly", 
        name: "TENERGY 05 TT Rubber", 
        price: "₹5,549", 
        originalPrice: "₹10,100", 
        img: "https://image2url.com/r2/default/images/1774177748375-1d1576e7-6cec-4ba1-9739-fbf2d787d033.webp",
        description: "Tenergy 05 is the original rubber in the Tenergy series, designed for players who thrive on topspin-heavy offensive play. Featuring High Tension and Spring Sponge technologies, it allows for explosive spin and consistent power close to or away from the table.",
        specs: { "Type": "High Tension Pimple-In", "Technology": "High Tension, Spring Sponge", "Speed": "83", "Spin": "76", "Arc": "79", "Sponge Hardness": "36", "Sheet Color": "Red, Black", "Sponge Thickness": "2.1", "Country Of Origin": "Japan" }
    },
    {
        id: 2, 
        brand: "Butterfly", 
        name: "TENERGY 05 FX TT Rubber", 
        price: "₹5,249", 
        originalPrice: "₹10,100", 
        img: "https://image2url.com/r2/default/images/1774178820648-4c1f5a96-4a5b-4593-84ee-9a8a601f9263.webp",
        description: "Tenergy FX produces a high level of control without losing high performance. Tenergy 05 FX combines High Tension technology with a version of Spring Sponge that produces a softer feeling.",
        specs: { "Type": "High Tension Pimple-In", "Technology": "High Tension, Spring Sponge", "Speed": "81", "Spin": "64", "Arc": "65", "Sponge Hardness": "32", "Sheet Color": "Red, Black", "Sponge Thickness": "2.1", "Country Of Origin": "Japan" }
    },
    {
        id: 3, 
        brand: "Butterfly", 
        name: "DIGNICS 09 C TT Rubber", 
        price: "₹6,449", 
        originalPrice: "₹12,900", 
        img: "https://image2url.com/r2/default/images/1774760646496-bb17b93b-38d7-41c6-8210-fbe82010fbff.webp",
        description: "Compatible friction and a high level bounce is realised thanks to the synergy effect between the original top sheet and a rather hard Spring Sponge X.",
        specs: { "Type": "High Friction High Tension Pimples-In", "Technology": "High Tension, Spring SpongeX", "Speed": "79", "Spin": "96", "Arc": "96", "Sponge Hardness": "44", "Sheet Color": "Red, Black", "Sponge Thickness": "2.1", "Country Of Origin": "Japan" }
    },
    {
        id: 4, 
        brand: "Butterfly", 
        name: "DIGNICS 05 TT Rubber", 
        price: "₹6,349", 
        originalPrice: "₹12,599", 
        img: "https://image2url.com/r2/default/images/1774759354874-8f030ab2-2725-43e1-b6e6-f6a16a9da50c.webp",
        description: "Dignics guides your play to a more advanced level. Adopting pimples code No. 05 recognized for its high spin performance.",
        specs: { "Type": "High Tension Pimples-In", "Technology": "High Tension, Spring SpongeX", "Speed": "86", "Spin": "85", "Arc": "88", "Sponge Hardness": "40", "Sheet Color": "Red, Black", "Sponge Thickness": "2.1", "Country Of Origin": "Japan" }
    },
    {
        id: 5, 
        brand: "Butterfly", 
        name: "Glayzer 09C TT Rubber", 
        price: "₹3,749", 
        originalPrice: "₹8,999", 
        img: "https://image2url.com/r2/default/images/1774761821421-e0b97df6-85c8-4965-a8f2-dde577922ff5.webp",
        description: "Grey Spring Sponge X is applied to Glayzer 09C. Strokes with a stable trajectory are made possible.",
        specs: { "Type": "High Tension High Friction Pimples-In", "Technology": "High Tension, Spring SpongeX", "Speed": "75", "Spin": "87", "Arc": "95", "Sponge Hardness": "42", "Sheet Color": "Red, Black", "Sponge Thickness": "2.1", "Country Of Origin": "Japan" }
    },
    {
        id: 6, 
        brand: "Butterfly", 
        name: "Glayzer TT Rubber", 
        price: "₹3,749", 
        originalPrice: "₹8,999", 
        img: "https://image2url.com/r2/default/images/1774762548074-05816153-4054-4102-9e58-476740c2c03c.webp",
        description: "Grey Spring Sponge X is applied to Glayzer. Power, generated by spin, is brought to the stroke.",
        specs: { "Type": "High Tension Pimples-In", "Technology": "High Tension, Spring SpongeX", "Speed": "81", "Spin": "83", "Arc": "82", "Sponge Hardness": "38", "Sheet Color": "Red, Black", "Sponge Thickness": "2.1", "Country Of Origin": "Japan" }
    },
    {
        id: 7, 
        brand: "Yinhe", 
        name: "Yinhe 01B TT Racket", 
        price: "₹1,299", 
        originalPrice: "₹2,999", 
        img: "https://image2url.com/r2/default/images/1774763442688-30d7b73d-d5d9-47e0-808f-a9db99c97303.webp",
        description: "Yinhe 01B Table Tennis Racket is made of high quality 5 ply layered wood. The rubbers used are ITTF approved.",
        specs: { "Type": "Pre-assembled", "Plys": "5", "Rubber": "ITTF Approved" }
    },
    {
        id: 8, 
        brand: "Butterfly", 
        name: "Timo Ball ALC TT Blade", 
        price: "₹12,399", 
        originalPrice: "₹22,999", 
        img: "https://image2url.com/r2/default/images/1774768625593-a5b6b5fb-322f-4050-87fa-c7583af47544.webp",
        description: "The Timo Boll ALC is a classic blade in the Butterfly line-up. Powerful attacking, as well as control, is made possible by applying Arylate-Carbon on the inside.",
        specs: { "Type": "Offensive Shakehand","Country Of Origin": "Japan" }
    },
{
        id: 9, 
        brand: "Butterfly", 
        name: "Butterfly Viscaria TT Blade", 
        price: "₹11,999", 
        originalPrice: "₹23,199", 
        img: "https://image2url.com/r2/default/images/1774768570953-875d005b-2db2-4255-9565-e21d729cf92f.webp",
        description: "Combining the advantages of high-tech fibers such as Arylate and carbon, the Viscaria blade is tailored masterfully towards variable attack with emphasis on spin. It is also the basis for many successful Arylate-Carbon based blades.",
        specs: { "Type": "Offensive Shakehand","Country Of Origin": "Japan" }
    }
];

// --- CORE APPLICATION LOGIC ---
const app = {
    activeBrandFilter: null,

    navigate: function(pageId) {
        document.querySelectorAll('.page-section').forEach(section => {
            section.classList.remove('active');
        });
        
        const target = document.getElementById(pageId);
        if(target) {
            target.classList.add('active');
            globalThis.scrollTo({ top: 0, behavior: 'smooth' }); // Fixed 'window' error
        }

        const navLinks = document.querySelector('.nav-links');
        if(navLinks && navLinks.classList.contains('active')) {
            navLinks.classList.remove('active');
        }

        if(pageId === 'products' && this.activeBrandFilter === null) {
            this.renderProducts();
        }
    },

    filterByBrand: function(brandName) {
        this.activeBrandFilter = brandName;
        this.navigate('products');
        this.renderProducts();
    },

    clearFilter: function() {
        this.activeBrandFilter = null;
        this.renderProducts();
    },

    showPurchaseModal: function(productId) {
        const product = dummyProducts.find(p => p.id === productId);
        if(product) {
            document.getElementById('modal-product-name').textContent = product.name;
            document.getElementById('purchase-modal').classList.add('active');
            
            const modalFooter = document.querySelector('.modal-footer');
            if(modalFooter) {
                modalFooter.innerHTML = `
                    <button class="btn-primary" style="width: 100%;" onclick="app.goToContact('${product.name}')">
                        Go to Contact Form
                    </button>
                `;
            }
        }
    },

    closeModal: function() {
        document.getElementById('purchase-modal').classList.remove('active');
    },

    goToContact: function(productName) {
        this.closeModal();
        this.navigate('contact');
        
        const messageBox = document.querySelector('.contact-form textarea');
        if(messageBox) {
            messageBox.value = `Hi ElevateSports team,\n\nI am interested in purchasing the ${productName}. Could you please let me know how I can proceed with the payment and delivery?\n\nThank you.`;
            messageBox.focus(); 
        }
    },

    setupContactForm: function() {
        const form = document.getElementById('elevate-contact-form');
        if(!form) return;

        form.addEventListener('submit', function(e) {
            e.preventDefault(); 
            
            const btn = document.getElementById('submit-btn');
            const originalText = btn ? btn.textContent : 'Send Message';
            
            if(btn) {
                btn.textContent = 'Sending...';
                btn.disabled = true;
                btn.style.opacity = '0.7';
            }

            const scriptURL = 'https://script.google.com/macros/s/AKfycbzAOL7Tc9kNqaIMeAwr0G9eQvyDceOKiLpUtWaV0-mAApWopEuAQYwQK2zuINfqWDRQ/exec'; 
            const formData = new FormData(form);

            fetch(scriptURL, { method: 'POST', body: formData })
                .then(_response => { // Fixed unused var error
                    alert('Success! Your message has been sent directly to our team.');
                    form.reset(); 
                    if(btn) {
                        btn.textContent = originalText;
                        btn.disabled = false;
                        btn.style.opacity = '1';
                    }
                })
                .catch(error => {
                    console.error('Error!', error.message);
                    alert('Oops! Something went wrong.');
                    if(btn) {
                        btn.textContent = originalText;
                        btn.disabled = false;
                        btn.style.opacity = '1';
                    }
                });
        });
    },

    viewProduct: function(productId) {
        const product = dummyProducts.find(p => p.id === productId);
        if (!product) return;

        let specsHTML = '';
        if (product.specs) {
            specsHTML = Object.entries(product.specs).map(([key, value]) => `
                <li><strong>${key}</strong> <span>${value}</span></li>
            `).join('');
        }

        const container = document.getElementById('product-details-container');
        container.innerHTML = `
            <div class="product-details-grid">
                <img src="${product.img}" alt="${product.name}" class="product-details-image">
                <div class="product-info">
                    <p class="product-info-brand">${product.brand}</p>
                    <h1 class="product-info-title">${product.name}</h1>
                    <p class="product-info-price">
                        ${product.originalPrice ? `<span style="text-decoration: line-through; color: #888; font-size: 1rem; margin-right: 8px;">${product.originalPrice}</span>` : ''}
                        ${product.price}
                    </p>
                    <p class="product-info-desc">${product.description}</p>
                    <ul class="product-specs">${specsHTML}</ul>
                    <button class="btn-primary" style="width: 100%; font-size: 1.2rem; padding: 15px;" onclick="app.showPurchaseModal(${product.id})">
                        Purchase Inquiry
                    </button>
                </div>
            </div>
        `;
        this.navigate('product-details');
    },

    renderProducts: function() {
        const grid = document.getElementById('products-grid');
        if (!grid) return;

        let productsToShow = this.activeBrandFilter 
            ? dummyProducts.filter(p => p.brand === this.activeBrandFilter) 
            : dummyProducts;

        let productsHTML = '';
        
        if (this.activeBrandFilter) {
            productsHTML += `
                <div style="grid-column: 1 / -1; display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; background: #222; padding: 15px; border-radius: 8px;">
                    <p style="margin: 0;">Showing: <strong>${this.activeBrandFilter}</strong></p>
                    <button class="btn-primary" onclick="app.clearFilter()" style="padding: 5px 15px;">Show All</button>
                </div>`;
        }

        productsHTML += productsToShow.map(product => `
            <article class="card">
                <img src="${product.img}" alt="${product.name}" class="card-img" loading="lazy">
                <div class="card-body">
                    <p style="font-size: 0.8rem; color: #888;">${product.brand}</p>
                    <h3>${product.name}</h3>
                    <p class="card-price">
                        ${product.originalPrice ? `<span style="text-decoration: line-through; color: #666; font-size: 0.85rem; margin-right: 5px;">${product.originalPrice}</span>` : ''}
                        ${product.price}
                    </p>
                    <button class="btn-primary" style="width: 100%;" onclick="app.viewProduct(${product.id})">View Details</button>
                </div>
            </article>
        `).join('');

        grid.innerHTML = productsHTML;
    },

    renderBrands: function() {
        const grid = document.getElementById('brands-grid');
        if(!grid) return;
        grid.innerHTML = dummyBrands.map(brand => `
            <div class="card" onclick="app.filterByBrand('${brand.name}')" style="display: flex; align-items: center; justify-content: center; height: 100px; cursor: pointer;">
                ${brand.logo}
            </div>
        `).join('');
    },

    init: function() {
        this.renderProducts();
        this.renderBrands();
        this.setupContactForm();
    }
};

document.addEventListener('DOMContentLoaded', () => app.init());
